export const styles = {
  container: { maxWidth: '620px', margin: '0 auto', padding: '0 12px', width: '100%', boxSizing: 'border-box' },
  navbar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px 0', borderBottom: '1px solid var(--color-border-dark)', position: 'sticky', top: 0, backgroundColor: 'var(--color-bg-dark)', zIndex: 100 },
  logo: { fontSize: '1.6rem', fontWeight: 'bold', color: '#00BFA6', letterSpacing: '-0.5px' },
  logoutBtn: { padding: '8px 16px', backgroundColor: 'transparent', color: '#ff4444', border: '1px solid #ff4444', borderRadius: '8px', cursor: 'pointer', fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '6px' },
  composeBox: { backgroundColor: 'var(--color-surface)', borderRadius: '16px', padding: '16px', margin: '12px 0', border: '1px solid var(--color-border-dark)', position: 'relative' },
  textarea: { width: '100%', height: '100px', border: 'none', outline: 'none', fontSize: '1rem', resize: 'none', fontFamily: 'inherit', backgroundColor: 'transparent', color: 'var(--color-text-main)' },
  composeFooter: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '8px' },
  charCount: { color: 'var(--color-text-dim)', fontSize: '0.85rem' },
  postBtn: { padding: '8px 28px', backgroundColor: '#00BFA6', color: 'white', border: 'none', borderRadius: '20px', fontSize: '0.95rem', cursor: 'pointer', fontWeight: 'bold' },
  feed: { display: 'flex', flexDirection: 'column', gap: '5px', paddingBottom: '32px' },
  post: { backgroundColor: 'var(--color-surface)', borderRadius: '16px', padding: '16px', border: '1px solid var(--color-border-dark)', transition: 'border-color 0.2s' },
  postHeader: { display: 'flex', justifyContent: 'space-between', marginBottom: '12px', alignItems: 'center' },
  username: { fontWeight: 'bold', color: '#00BFA6', fontSize: '0.95rem' },
  date: { color: 'var(--color-text-dim)', fontSize: '0.8rem' },
  postContent: { fontSize: '1rem', lineHeight: '1.6', color: 'var(--color-text-main)' },
  actions: { display: 'flex', gap: '8px', marginTop: '16px', alignItems: 'center', borderTop: '1px solid var(--color-border-dark)', paddingTop: '12px' },
  actionBtn: { background: 'none', border: 'none', cursor: 'pointer', fontSize: '0.9rem', padding: '6px 12px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '6px', transition: 'background 0.2s' },
  deleteBtn: { marginLeft: 'auto', padding: '6px 14px', backgroundColor: 'transparent', color: '#ff4444', border: '1px solid #ff4444', borderRadius: '8px', cursor: 'pointer', fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '6px' },
  commentsSection: { marginTop: '16px', borderTop: '1px solid var(--color-border-dark)', paddingTop: '16px' },
  comment: { marginBottom: '10px', padding: '12px', backgroundColor: 'var(--color-bg-dark)', borderRadius: '10px', border: '1px solid var(--color-border-dark)' },
  commentHeader: { display: 'flex', justifyContent: 'space-between', marginBottom: '6px', alignItems: 'center' },
  commentUsername: { fontWeight: 'bold', fontSize: '0.85rem', color: '#00BFA6' },
  commentContent: { fontSize: '0.9rem', color: 'var(--color-text-reply)', lineHeight: '1.5' },
  deleteCommentBtn: { background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-text-dim)', fontSize: '0.8rem', padding: '2px 6px', borderRadius: '4px' },
  commentInputRow: { display: 'flex', gap: '8px', marginTop: '12px' },
  commentInput: { flex: 1, padding: '10px 14px', borderRadius: '10px', border: '1px solid var(--color-border-dark)', fontSize: '0.9rem', outline: 'none', backgroundColor: 'var(--color-bg-dark)', color: 'var(--color-text-main)' },
  commentBtn: { padding: '10px 16px', backgroundColor: '#00BFA6', color: 'white', border: 'none', borderRadius: '10px', cursor: 'pointer', fontSize: '0.9rem' },
  empty: { textAlign: 'center', color: 'var(--color-text-dim)', marginTop: '2rem', fontSize: '0.95rem' },
  composeActions: { display: 'flex', gap: '4px', alignItems: 'center' },
  composeRight: { display: 'flex', alignItems: 'center', gap: '12px' },
  mediaBtn: { background: 'none', border: 'none', cursor: 'pointer', color: '#00BFA6', fontSize: '1.1rem', padding: '6px 10px', borderRadius: '8px' },
  gifLabel: { fontWeight: 'bold', fontSize: '0.85rem', color: '#00BFA6', border: '2px solid #00BFA6', borderRadius: '6px', padding: '1px 5px' },
  previewWrapper: { position: 'relative', marginTop: '10px', display: 'inline-block', width: '100%' },
  previewImg: { maxWidth: '100%', maxHeight: '300px', borderRadius: '12px', border: '1px solid var(--color-border-dark)', display: 'block' },
  removeImg: { position: 'absolute', top: '8px', right: '8px', backgroundColor: 'rgba(0,0,0,0.7)', border: 'none', borderRadius: '50%', width: '28px', height: '28px', cursor: 'pointer', color: 'white', fontSize: '0.85rem', display: 'flex', alignItems: 'center', justifyContent: 'center' },
}