export const styles = {
  container: { maxWidth: '620px', margin: '0 auto', padding: '0 16px', width: '100%' },
  header: { display: 'flex', alignItems: 'center', gap: '12px', padding: '24px 0 16px', borderBottom: '1px solid var(--color-border-dark)', position: 'sticky', top: 0, backgroundColor: 'var(--color-bg-dark)', zIndex: 10 },
  title: { fontSize: '1.3rem', fontWeight: 'bold', color: 'var(--color-text-main)' },
  count: { backgroundColor: '#00BFA6', color: 'white', borderRadius: '20px', padding: '2px 10px', fontSize: '0.8rem', fontWeight: 'bold' },
  list: { paddingTop: '8px', paddingBottom: '32px' },
  skeletonList: { paddingTop: '8px', paddingBottom: '32px' },
  skeletonRow: { display: 'flex', alignItems: 'center', gap: '12px', padding: '12px 0' },
  skeletonIcon: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    background: 'linear-gradient(90deg, var(--color-surface) 0%, var(--color-border-dark) 50%, var(--color-surface) 100%)',
    backgroundSize: '200% 100%',
    animation: 'notif-skeleton 1.4s ease-in-out infinite',
    flexShrink: 0
  },
  skeletonInfo: { flex: 1, display: 'flex', flexDirection: 'column', gap: '6px' },
  skeletonLineUser: {
    width: '35%',
    height: '10px',
    borderRadius: '999px',
    background: 'linear-gradient(90deg, var(--color-surface) 0%, var(--color-border-dark) 50%, var(--color-surface) 100%)',
    backgroundSize: '200% 100%',
    animation: 'notif-skeleton 1.4s ease-in-out infinite'
  },
  skeletonLineText: {
    width: '70%',
    height: '10px',
    borderRadius: '999px',
    background: 'linear-gradient(90deg, var(--color-surface) 0%, var(--color-border-dark) 50%, var(--color-surface) 100%)',
    backgroundSize: '200% 100%',
    animation: 'notif-skeleton 1.4s ease-in-out infinite'
  },
  skeletonLineMeta: {
    width: '20%',
    height: '9px',
    borderRadius: '999px',
    background: 'linear-gradient(90deg, var(--color-surface) 0%, var(--color-border-dark) 50%, var(--color-surface) 100%)',
    backgroundSize: '200% 100%',
    animation: 'notif-skeleton 1.4s ease-in-out infinite'
  },
  message: { textAlign: 'center', color: 'var(--color-text-dim)', marginTop: '2rem' },
  emptyState: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', marginTop: '80px', gap: '16px' },
  emptyIcon: { fontSize: '3rem', color: 'var(--color-border-dark)' },
  emptyText: { color: 'var(--color-text-dim)', fontSize: '1rem' },
  notification: { display: 'flex', alignItems: 'center', gap: '12px', padding: '16px', borderBottom: '1px solid var(--color-border-dark)', cursor: 'pointer', borderRadius: '12px' },
  unread: { backgroundColor: 'var(--color-surface)' },
  left: { display: 'flex', alignItems: 'center', gap: '10px', flexShrink: 0 },
  avatarWrapper: {
    position: 'relative',
    width: '40px',
    height: '40px',
    flexShrink: 0
  },
  avatarCircle: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    backgroundColor: 'var(--color-border-dark)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#cbd5f5',
    fontWeight: 'bold',
    fontSize: '0.9rem',
    flexShrink: 0,
    overflow: 'hidden'
  },
  typeIcon: {
    position: 'absolute',
    right: '-2px',
    bottom: '-2px',
    width: '18px',
    height: '18px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '0.7rem',
    boxSizing: 'border-box'
  },
  notifInfo: { flex: 1, fontSize: '0.95rem', color: 'var(--color-text-main)', lineHeight: '1.5', display: 'flex', flexDirection: 'column', gap: '2px' },
  notifLine: { display: 'flex', alignItems: 'baseline', flexWrap: 'wrap', gap: '4px' },
  sender: { fontWeight: 'bold', color: 'var(--color-text-main)' },
  notifText: { color: 'var(--color-text-main)' },
  notifDate: { color: 'var(--color-text-dim)', fontSize: '0.8rem', marginLeft: '6px' },
  deleteBtn: { background: 'none', border: 'none', cursor: 'pointer', color: 'var(--color-text-dim)', fontSize: '0.85rem', padding: '4px 8px', borderRadius: '6px', flexShrink: 0 },
}