export const styles = {
  container: { maxWidth: '620px', margin: '0 auto', padding: '0 12px', width: '100%', boxSizing: 'border-box' },
  loading: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100vh', color: '#00BFA6', fontSize: '1rem' },

  navbar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px 0', borderBottom: '1px solid var(--color-border-dark)', position: 'sticky', top: 0, backgroundColor: 'var(--color-bg-dark)', zIndex: 100 },
  logo: { fontSize: '1.4rem', fontWeight: 'bold', color: '#00BFA6' },
  backBtn: { padding: '8px 16px', backgroundColor: 'transparent', color: '#00BFA6', border: '1px solid #00BFA6', borderRadius: '8px', cursor: 'pointer', fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '6px' },
  profileCard: { backgroundColor: 'var(--color-surface)', borderRadius: '16px', padding: '24px', margin: '20px 0', border: '1px solid var(--color-border-dark)', display: 'flex', gap: '20px', alignItems: 'flex-start' },
  avatar: { width: '72px', height: '72px', borderRadius: '50%', backgroundColor: '#00BFA6', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '2rem', fontWeight: 'bold', color: 'white', flexShrink: 0 },
  profileInfo: { flex: 1 },
  username: { fontSize: '1.3rem', fontWeight: 'bold', color: 'var(--color-text-main)', marginBottom: '4px' },
  joinDate: { color: 'var(--color-text-dim)', fontSize: '0.85rem', marginBottom: '10px', display: 'flex', alignItems: 'center', gap: '6px' },
  bio: { color: '#aaa', fontSize: '0.95rem', lineHeight: '1.5', marginBottom: '16px' },
  bioEdit: { display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '16px' },
  bioInput: { padding: '10px', borderRadius: '10px', border: '1px solid var(--color-border-dark)', backgroundColor: 'var(--color-bg-dark)', color: 'var(--color-text-main)', fontSize: '0.95rem', resize: 'none', height: '80px', outline: 'none', fontFamily: 'inherit' },
  bioActions: { display: 'flex', gap: '8px' },
  saveBtn: { padding: '6px 16px', backgroundColor: '#00BFA6', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '0.85rem', fontWeight: 'bold' },
  cancelBtn: { padding: '6px 16px', backgroundColor: 'transparent', color: '#888', border: '1px solid var(--color-border-dark)', borderRadius: '8px', cursor: 'pointer', fontSize: '0.85rem' },
  stats: { display: 'flex', gap: '24px', marginBottom: '16px' },
  stat: { display: 'flex', flexDirection: 'column', alignItems: 'center' },
  statNumber: { fontWeight: 'bold', fontSize: '1.1rem', color: 'var(--color-text-main)' },
  statLabel: { color: 'var(--color-text-dim)', fontSize: '0.8rem' },
  profileActions: { display: 'flex', gap: '8px' },
  editBtn: { padding: '8px 16px', backgroundColor: 'transparent', color: '#00BFA6', border: '1px solid #00BFA6', borderRadius: '8px', cursor: 'pointer', fontSize: '0.9rem', display: 'flex', alignItems: 'center', gap: '6px' },
  followBtn: { padding: '8px 24px', borderRadius: '8px', cursor: 'pointer', fontSize: '0.9rem', fontWeight: 'bold' },
  postsSection: { marginBottom: '32px' },
  postsTitle: { fontSize: '1.1rem', fontWeight: 'bold', color: 'var(--color-text-main)', marginBottom: '16px', paddingBottom: '12px', borderBottom: '1px solid var(--color-border-dark)' },
  post: { backgroundColor: 'var(--color-surface)', borderRadius: '16px', padding: '20px', border: '1px solid var(--color-border-dark)', marginBottom: '12px' },
  postHeader: { display: 'flex', justifyContent: 'space-between', marginBottom: '10px', alignItems: 'center' },
  postUsername: { fontWeight: 'bold', color: '#00BFA6', fontSize: '0.95rem' },
  postDate: { color: 'var(--color-text-dim)', fontSize: '0.8rem' },
  postContent: { fontSize: '1rem', lineHeight: '1.6', color: 'var(--color-text-main)' },
  empty: { textAlign: 'center', color: 'var(--color-text-dim)', marginTop: '2rem' },
  displayName: { fontSize: '1.3rem', fontWeight: 'bold', color: 'var(--color-text-main)', marginBottom: '2px' },
  usernameHandle: { color: '#00BFA6', fontSize: '0.85rem', marginBottom: '10px' },
  noPosts: { textAlign: 'center', color: 'var(--color-text-dim)', marginTop: '2rem' },
  avatarLarge: { width: '80px', height: '80px', borderRadius: '50%', backgroundColor: '#00BFA6', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '2rem', fontWeight: 'bold', color: 'white', flexShrink: 0, cursor: 'pointer' },
  avatarImg: { width: '80px', height: '80px', borderRadius: '50%', objectFit: 'cover', border: '3px solid #00BFA6' },
  avatarUploadBtn: { position: 'absolute', bottom: 0, right: 0, width: '28px', height: '28px', borderRadius: '50%', backgroundColor: '#00BFA6', border: 'none', cursor: 'pointer', color: 'white', fontSize: '0.75rem', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  avatarOverlay: { position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', borderRadius: '50%', backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'opacity 0.2s ease' },
  avatarViewerOverlay: { position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh', backgroundColor: 'rgba(0,0,0,0.85)', zIndex: 99999, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  avatarViewerContent: { position: 'relative' },
  avatarViewerClose: { position: 'absolute', top: '-40px', right: 0, background: 'none', border: 'none', color: 'white', fontSize: '1.5rem', cursor: 'pointer', padding: '4px 8px' },
  avatarViewerImg: { maxWidth: '80vw', maxHeight: '80vh', objectFit: 'contain', display: 'block' },
}