export const styles = {
  container: { maxWidth: '620px', margin: '0 auto', padding: '0 12px', width: '100%', boxSizing: 'border-box' },
  header: { padding: '24px 0 16px', borderBottom: '1px solid var(--color-border-dark)', position: 'sticky', top: 0, backgroundColor: 'var(--color-bg-dark)', zIndex: 10 },
  title: { fontSize: '1.3rem', fontWeight: 'bold', color: 'var(--color-text-main)', marginBottom: '16px' },
  searchInput: { width: '100%', padding: '12px 16px', borderRadius: '12px', border: '1px solid var(--color-border-dark)', backgroundColor: 'var(--color-surface)', color: 'var(--color-text-main)', fontSize: '1rem', outline: 'none', fontFamily: 'inherit' },
  tabs: { display: 'flex', gap: '4px', padding: '12px 0', borderBottom: '1px solid var(--color-border-dark)' },
  tab: { padding: '8px 20px', borderRadius: '8px', border: 'none', backgroundColor: 'transparent', color: '#888', fontSize: '0.95rem', cursor: 'pointer' },
  tabActive: { backgroundColor: 'var(--color-surface)', color: '#00BFA6', fontWeight: 'bold' },
  results: { paddingTop: '16px', paddingBottom: '32px' },
  sectionLabel: { color: 'var(--color-text-dim)', fontSize: '0.85rem', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '12px', marginTop: '8px' },
  message: { textAlign: 'center', color: 'var(--color-text-dim)', marginTop: '2rem', fontSize: '0.95rem' },
  userCard: { display: 'flex', alignItems: 'center', gap: '12px', padding: '16px', backgroundColor: 'var(--color-surface)', borderRadius: '16px', border: '1px solid var(--color-border-dark)', marginBottom: '12px', cursor: 'pointer' },
  userAvatar: { flexShrink: 0 },
  userInfo: { display: 'flex', flexDirection: 'column', flex: 1 },
  userName: { fontWeight: 'bold', color: 'var(--color-text-main)', fontSize: '0.95rem' },
  userHandle: { color: '#00BFA6', fontSize: '0.85rem' },
  userBio: { color: '#888', fontSize: '0.85rem', marginTop: '4px' },
  emptyState: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', marginTop: '80px', gap: '16px' },
  emptyIcon: { fontSize: '3rem', color: 'var(--color-border-dark)' },
  emptyText: { color: 'var(--color-text-dim)', fontSize: '1rem' },
  userAvatarImg: { width: '48px', height: '48px', borderRadius: '50%', objectFit: 'cover', border: '2px solid var(--color-border-dark)' },
  userAvatarFallback: { width: '48px', height: '48px', borderRadius: '50%', backgroundColor: '#00BFA6', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.3rem', fontWeight: 'bold', color: 'white', flexShrink: 0 },
}