export const styles = {
  container: { maxWidth: '620px', margin: '0 auto', padding: '0 16px', width: '100%' },
  header: { padding: '24px 0 16px', borderBottom: '1px solid var(--color-border-dark)', position: 'sticky', top: 0, backgroundColor: 'var(--color-bg-dark)', zIndex: 10, marginBottom: '24px' },
  title: { fontSize: '1.3rem', fontWeight: 'bold', color: 'var(--color-text-main)' },
  section: { backgroundColor: 'var(--color-surface)', borderRadius: '16px', padding: '24px', marginBottom: '16px', border: '1px solid var(--color-border-dark)' },
  sectionTitle: { fontSize: '1rem', fontWeight: 'bold', color: 'var(--color-text-main)', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' },
  input: { width: '100%', padding: '12px 16px', borderRadius: '10px', border: '1px solid var(--color-border-dark)', backgroundColor: 'var(--color-bg-dark)', color: 'var(--color-text-main)', fontSize: '0.95rem', outline: 'none', fontFamily: 'inherit' },
  saveBtn: { marginTop: '12px', padding: '10px 24px', backgroundColor: '#00BFA6', color: 'white', border: 'none', borderRadius: '10px', cursor: 'pointer', fontSize: '0.95rem', fontWeight: 'bold' },
  error: { color: '#ff4444', fontSize: '0.85rem', marginTop: '8px' },
  successMsg: { color: '#00BFA6', fontSize: '0.85rem', marginTop: '8px' },
  dangerText: { color: '#888', fontSize: '0.9rem', marginBottom: '16px', lineHeight: '1.5' },
  deleteBtn: { padding: '10px 24px', backgroundColor: 'transparent', color: '#ff4444', border: '1px solid #ff4444', borderRadius: '10px', cursor: 'pointer', fontSize: '0.95rem', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '8px' },
  modalOverlay: { position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh', backgroundColor: 'rgba(0,0,0,0.6)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 9999 },
  modal: { backgroundColor: 'var(--color-surface)', borderRadius: '16px', padding: '24px', border: '1px solid var(--color-border-dark)', width: '320px', boxShadow: '0 8px 32px rgba(0,0,0,0.4)' },
  modalTitle: { color: '#ff4444', fontSize: '1.1rem', fontWeight: 'bold', marginBottom: '8px' },
  modalText: { color: '#888', fontSize: '0.9rem', marginBottom: '20px', lineHeight: '1.5' },
  modalActions: { display: 'flex', gap: '10px', justifyContent: 'flex-end' },
  cancelBtn: { padding: '8px 16px', backgroundColor: 'transparent', color: '#888', border: '1px solid var(--color-border-dark)', borderRadius: '8px', cursor: 'pointer', fontSize: '0.9rem' },
  confirmBtn: { padding: '8px 16px', backgroundColor: '#ff4444', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer', fontSize: '0.9rem', fontWeight: 'bold' },
  hint: { color: 'var(--color-text-dim)', fontSize: '0.85rem', marginBottom: '12px', lineHeight: '1.5' },
}