export const styles = {
    container: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', backgroundColor: 'var(--color-bg-dark)', padding: '16px' },
    content: { width: '100%', maxWidth: '440px', backgroundColor: 'var(--color-surface)', padding: '2.5rem', borderRadius: '20px', boxShadow: '0 12px 40px rgba(0,0,0,0.5)', border: '1px solid var(--color-border-dark)' },
    header: { marginBottom: '2rem', textAlign: 'center' },
    logo: { fontSize: '2.2rem', color: '#00BFA6', marginBottom: '8px', display: 'block' },
    title: { fontSize: '1.4rem', fontWeight: 'bold', color: 'var(--color-text-main)' },
    accountCard: { backgroundColor: 'var(--color-bg-dark)', borderRadius: '12px', padding: '14px 16px', marginBottom: '12px', border: '1px solid var(--color-border-dark)', display: 'flex', alignItems: 'center', gap: '14px', transition: 'all 0.2s ease', cursor: 'pointer', position: 'relative' },
    activeCard: { borderColor: '#00BFA6', backgroundColor: 'rgba(0, 191, 166, 0.05)' },
    avatar: { width: '42px', height: '42px', borderRadius: '50%', backgroundColor: '#00BFA6', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.2rem', fontWeight: 'bold', color: 'white', flexShrink: 0 },
    avatarImg: { width: '42px', height: '42px', borderRadius: '50%', objectFit: 'cover', border: '1px solid var(--color-border-dark)', flexShrink: 0 },
    accountInfo: { flex: 1, overflow: 'hidden' },
    displayName: { fontWeight: 'bold', color: 'var(--color-text-main)', fontSize: '0.9rem', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
    username: { color: '#888', fontSize: '0.8rem' },
    activeBadge: { position: 'absolute', top: '-10px', right: '16px', backgroundColor: '#00BFA6', color: 'white', borderRadius: '20px', padding: '2px 10px', fontSize: '0.65rem', fontWeight: 'bold', border: '2px solid var(--color-surface)', boxShadow: '0 2px 8px rgba(0,0,0,0.3)' },
    cardActions: { display: 'flex', gap: '8px', alignItems: 'center', flexShrink: 0 },
    switchBtn: { padding: '6px 12px', backgroundColor: '#00BFA6', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '0.8rem', fontWeight: 'bold' },
    feedBtn: { padding: '6px 12px', backgroundColor: 'transparent', color: '#00BFA6', border: '1px solid #00BFA6', borderRadius: '6px', cursor: 'pointer', fontSize: '0.8rem', fontWeight: 'bold' },
    logoutBtn: { backgroundColor: 'transparent', color: '#ff4444', border: 'none', cursor: 'pointer', fontSize: '0.8rem', padding: '4px 8px', transition: 'color 0.2s', fontWeight: '500' },
    addAccount: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', padding: '14px', color: '#00BFA6', fontSize: '0.9rem', cursor: 'pointer', fontWeight: 'bold', borderRadius: '10px', border: '1px dashed var(--color-border-dark)', marginTop: '16px', transition: 'all 0.2s' },
    backBtn: { position: 'absolute', top: '24px', left: '24px', color: '#00BFA6', cursor: 'pointer', fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '8px', textDecoration: 'none', background: 'none', border: '1px solid #00BFA6', padding: '6px 12px', borderRadius: '8px', fontWeight: 'bold' },
    switchingOverlay: { position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh', backgroundColor: 'rgba(15,17,23,0.9)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 9999, flexDirection: 'column', gap: '16px' },
    switchingText: { color: '#00BFA6', fontSize: '1.1rem', fontWeight: 'bold' },
    notification: { position: 'fixed', top: '32px', left: '50%', transform: 'translateX(-50%)', backgroundColor: '#ff4444', color: 'white', padding: '12px 24px', borderRadius: '12px', fontWeight: 'bold', boxShadow: '0 8px 24px rgba(255,68,68,0.4)', zIndex: 10000, animation: 'fadeInDown 0.3s ease forwards' },
    modalOverlay: { position: 'fixed', top: 0, left: 0, width: '100vw', height: '100vh', backgroundColor: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 10001, backdropFilter: 'blur(4px)' },
    modalContent: { backgroundColor: 'var(--color-surface)', padding: '2rem', borderRadius: '20px', width: '90%', maxWidth: '400px', border: '1px solid var(--color-border-dark)', textAlign: 'center' },
    modalTitle: { fontSize: '1.25rem', fontWeight: 'bold', color: 'var(--color-text-main)', marginBottom: '12px' },
    modalText: { fontSize: '0.95rem', color: '#888', marginBottom: '1.5rem', lineHeight: '1.5' },
    modalActions: { display: 'flex', gap: '12px', justifyContent: 'center' },
    confirmBtn: { padding: '10px 20px', backgroundColor: '#ff4444', color: 'white', border: 'none', borderRadius: '10px', fontWeight: 'bold', cursor: 'pointer', flex: 1 },
    cancelBtn: { padding: '10px 20px', backgroundColor: 'transparent', color: 'var(--color-text-main)', border: '1px solid var(--color-border-dark)', borderRadius: '10px', fontWeight: 'bold', cursor: 'pointer', flex: 1 },
}
